export const contribuitors = [
  {
    login: 'tobydox',
    id: 3300739,
    node_id: 'MDQ6VXNlcjMzMDA3Mzk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3300739?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tobydox',
    html_url: 'https://github.com/tobydox',
    followers_url: 'https://api.github.com/users/tobydox/followers',
    following_url:
      'https://api.github.com/users/tobydox/following{/other_user}',
    gists_url: 'https://api.github.com/users/tobydox/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/tobydox/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tobydox/subscriptions',
    organizations_url: 'https://api.github.com/users/tobydox/orgs',
    repos_url: 'https://api.github.com/users/tobydox/repos',
    events_url: 'https://api.github.com/users/tobydox/events{/privacy}',
    received_events_url: 'https://api.github.com/users/tobydox/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
    contributions: 2396,
  },
  {
    login: 'diizy',
    id: 6368868,
    node_id: 'MDQ6VXNlcjYzNjg4Njg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6368868?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/diizy',
    html_url: 'https://github.com/diizy',
    followers_url: 'https://api.github.com/users/diizy/followers',
    following_url: 'https://api.github.com/users/diizy/following{/other_user}',
    gists_url: 'https://api.github.com/users/diizy/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/diizy/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/diizy/subscriptions',
    organizations_url: 'https://api.github.com/users/diizy/orgs',
    repos_url: 'https://api.github.com/users/diizy/repos',
    events_url: 'https://api.github.com/users/diizy/events{/privacy}',
    received_events_url: 'https://api.github.com/users/diizy/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
    contributions: 762,
  },
  {
    login: 'tresf',
    id: 6345473,
    node_id: 'MDQ6VXNlcjYzNDU0NzM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6345473?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tresf',
    html_url: 'https://github.com/tresf',
    followers_url: 'https://api.github.com/users/tresf/followers',
    following_url: 'https://api.github.com/users/tresf/following{/other_user}',
    gists_url: 'https://api.github.com/users/tresf/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/tresf/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tresf/subscriptions',
    organizations_url: 'https://api.github.com/users/tresf/orgs',
    repos_url: 'https://api.github.com/users/tresf/repos',
    events_url: 'https://api.github.com/users/tresf/events{/privacy}',
    received_events_url: 'https://api.github.com/users/tresf/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
    contributions: 612,
  },
  {
    login: 'lukas-w',
    id: 2879917,
    node_id: 'MDQ6VXNlcjI4Nzk5MTc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2879917?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lukas-w',
    html_url: 'https://github.com/lukas-w',
    followers_url: 'https://api.github.com/users/lukas-w/followers',
    following_url:
      'https://api.github.com/users/lukas-w/following{/other_user}',
    gists_url: 'https://api.github.com/users/lukas-w/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/lukas-w/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/lukas-w/subscriptions',
    organizations_url: 'https://api.github.com/users/lukas-w/orgs',
    repos_url: 'https://api.github.com/users/lukas-w/repos',
    events_url: 'https://api.github.com/users/lukas-w/events{/privacy}',
    received_events_url: 'https://api.github.com/users/lukas-w/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
    contributions: 506,
  },
  {
    login: 'michaelgregorius',
    id: 9293269,
    node_id: 'MDQ6VXNlcjkyOTMyNjk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/9293269?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/michaelgregorius',
    html_url: 'https://github.com/michaelgregorius',
    followers_url: 'https://api.github.com/users/michaelgregorius/followers',
    following_url:
      'https://api.github.com/users/michaelgregorius/following{/other_user}',
    gists_url: 'https://api.github.com/users/michaelgregorius/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/michaelgregorius/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/michaelgregorius/subscriptions',
    organizations_url: 'https://api.github.com/users/michaelgregorius/orgs',
    repos_url: 'https://api.github.com/users/michaelgregorius/repos',
    events_url:
      'https://api.github.com/users/michaelgregorius/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/michaelgregorius/received_events',
    type: 'User',
    user_view_type: 'public',
    site_admin: false,
    contributions: 250,
  },
  {
    login: 'Others',
    contributions: 2440,
    isOthers: true,
  },
];
